Added bash autocomplete #48

diff --git a/.scripts/verify b/.scripts/verify
--- a/.scripts/verify
+++ b/.scripts/verify
@@ -1,10 +1,30 @@
 #!/bin/bash
-
-set -e
-
+echo "[1/4] Running format check..."
 .scripts/format-check
+if [ $? -ne 0 ]; then
+    echo "[1/4] 🚨 Format check failed."
+    exit 1
+fi
+
+echo "[2/4] Running lint check..."
 .scripts/lint
+if [ $? -ne 0 ]; then
+    echo "[2/4] 🚨 Lint check failed."
+    exit 1
+fi
+
+echo "[3/4] Running test check..."
 .scripts/test
+if [ $? -ne 0 ]; then
+    echo "[3/4] 🚨 Tests failed."
+    exit 1
+fi
+
+echo "[4/4] Running build check..."
 .scripts/build
+if [ $? -ne 0 ]; then
+    echo "[4/4] 🚨 Build failed."
+    exit 1
+fi
 
 echo "Verified successfully ✅✅✅"
